### ISSUE TITLE
Executing source code 

### ISSUE THREAD

**Issue by LJ-water** [MMehdiMousavi/AIP#4]
Hi, thanks for sharing this amazing work! 

I'm trying to open your code on UE, but couldn't figure out how to access AIP's assets (such as rooms). 
Could you please elaborate on how to run the code in UE? Thanks!

**Comment by MMehdiMousavi** [comment]
Hi, you can download the map project directly from unreal engine.  look for it in the learn tab in the epic games launcher, its called 'realistic rendering'. then you can import the AIP_Core Files and start using the AIP features in there. this would work with any project, by the way.
