### ISSUE TITLE
ERROR No such file directory: 'ProbeLog\\look_rotate.txt'

### ISSUE THREAD

**Issue by aleynadikall** [MMehdiMousavi/AIP#5]
When I run the Probe.py file for my Unreal Engine 5.2 project, I get the following error. How can I access the 'look_rotate.txt' file?
Thank you.
![image](https://github.com/MMehdiMousavi/AIPlayground/assets/79109512/4ca6511a-bef8-422d-b8d9-04a0f11e499e)

**Comment by MMehdiMousavi** [comment]
hi, this indicates the folder or look file is missing, which means either the moves arent generated or the files are moved somewhere else. 

try uncommenting `generate_moves` and running it again.
